# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created: Mon May 30 14:51:50 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 800)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/viper.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(209, 9, 581, 531))
        self.widget.setObjectName("widget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuAnalysis = QtGui.QMenu(self.menubar)
        self.menuAnalysis.setObjectName("menuAnalysis")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setEnabled(True)
        self.toolBar.setIconSize(QtCore.QSize(40, 40))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/files/File-New-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon1)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/files/open-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon2)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/files/save-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon3)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionExit = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/files/Log-Out-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon4)
        self.actionExit.setObjectName("actionExit")
        self.actionAdd_fibres = QtGui.QAction(MainWindow)
        self.actionAdd_fibres.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/files/addFibers.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionAdd_fibres.setIcon(icon5)
        self.actionAdd_fibres.setObjectName("actionAdd_fibres")
        self.actionCompact = QtGui.QAction(MainWindow)
        self.actionCompact.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/files/compactMicro.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCompact.setIcon(icon6)
        self.actionCompact.setObjectName("actionCompact")
        self.actionPlotSettings = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/files/plotSettings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlotSettings.setIcon(icon7)
        self.actionPlotSettings.setObjectName("actionPlotSettings")
        self.actionHelp = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/files/about-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon8)
        self.actionHelp.setObjectName("actionHelp")
        self.actionPattern = QtGui.QAction(MainWindow)
        self.actionPattern.setEnabled(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/files/patterned.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPattern.setIcon(icon9)
        self.actionPattern.setObjectName("actionPattern")
        self.actionEditManual = QtGui.QAction(MainWindow)
        self.actionEditManual.setEnabled(False)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/files/pointer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditManual.setIcon(icon10)
        self.actionEditManual.setObjectName("actionEditManual")
        self.actionRefresh = QtGui.QAction(MainWindow)
        self.actionRefresh.setEnabled(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/files/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefresh.setIcon(icon11)
        self.actionRefresh.setObjectName("actionRefresh")
        self.actionSaveSimscreen = QtGui.QAction(MainWindow)
        self.actionSaveSimscreen.setVisible(True)
        self.actionSaveSimscreen.setIconVisibleInMenu(True)
        self.actionSaveSimscreen.setObjectName("actionSaveSimscreen")
        self.actionOpenSimscreen = QtGui.QAction(MainWindow)
        self.actionOpenSimscreen.setVisible(True)
        self.actionOpenSimscreen.setObjectName("actionOpenSimscreen")
        self.actionNNA = QtGui.QAction(MainWindow)
        self.actionNNA.setObjectName("actionNNA")
        self.actionDiameters = QtGui.QAction(MainWindow)
        self.actionDiameters.setObjectName("actionDiameters")
        self.actionRDF = QtGui.QAction(MainWindow)
        self.actionRDF.setObjectName("actionRDF")
        self.actionLocal_volume_fraction = QtGui.QAction(MainWindow)
        self.actionLocal_volume_fraction.setObjectName("actionLocal_volume_fraction")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionSaveSimscreen)
        self.menuFile.addAction(self.actionOpenSimscreen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionAdd_fibres)
        self.menuEdit.addAction(self.actionCompact)
        self.menuEdit.addAction(self.actionPattern)
        self.menuEdit.addAction(self.actionEditManual)
        self.menuView.addAction(self.actionPlotSettings)
        self.menuView.addAction(self.actionRefresh)
        self.menuHelp.addAction(self.actionHelp)
        self.menuAnalysis.addSeparator()
        self.menuAnalysis.addAction(self.actionDiameters)
        self.menuAnalysis.addAction(self.actionNNA)
        self.menuAnalysis.addAction(self.actionRDF)
        self.menuAnalysis.addSeparator()
        self.menuAnalysis.addAction(self.actionLocal_volume_fraction)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuAnalysis.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAdd_fibres)
        self.toolBar.addAction(self.actionCompact)
        self.toolBar.addAction(self.actionPattern)
        self.toolBar.addAction(self.actionEditManual)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPlotSettings)
        self.toolBar.addAction(self.actionRefresh)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHelp)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAnalysis.setTitle(QtGui.QApplication.translate("MainWindow", "Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setToolTip(QtGui.QApplication.translate("MainWindow", "Creates a new microstructure", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setStatusTip(QtGui.QApplication.translate("MainWindow", "Click to create a new microstructure", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setToolTip(QtGui.QApplication.translate("MainWindow", "Opens a microstructure file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setStatusTip(QtGui.QApplication.translate("MainWindow", "Click to open a microstructure file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setToolTip(QtGui.QApplication.translate("MainWindow", "Saves current microstructure", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setStatusTip(QtGui.QApplication.translate("MainWindow", "Click to save current microstructure", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as.setText(QtGui.QApplication.translate("MainWindow", "Save as...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setStatusTip(QtGui.QApplication.translate("MainWindow", "Click to quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_fibres.setText(QtGui.QApplication.translate("MainWindow", "Add fibres", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_fibres.setToolTip(QtGui.QApplication.translate("MainWindow", "Add fibres to the microstructure", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_fibres.setStatusTip(QtGui.QApplication.translate("MainWindow", "Add fibres to the microstructure", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompact.setText(QtGui.QApplication.translate("MainWindow", "Compact RVE", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompact.setToolTip(QtGui.QApplication.translate("MainWindow", "Compacts the microstructure", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompact.setStatusTip(QtGui.QApplication.translate("MainWindow", "Compacts the microstructure", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlotSettings.setText(QtGui.QApplication.translate("MainWindow", "Plot settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlotSettings.setToolTip(QtGui.QApplication.translate("MainWindow", "Customize plot settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlotSettings.setStatusTip(QtGui.QApplication.translate("MainWindow", "Customize plot settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setToolTip(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setStatusTip(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPattern.setText(QtGui.QApplication.translate("MainWindow", "Patterned Microstructure", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPattern.setToolTip(QtGui.QApplication.translate("MainWindow", "Generate periodic pattern", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPattern.setStatusTip(QtGui.QApplication.translate("MainWindow", "Generate periodic pattern", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditManual.setText(QtGui.QApplication.translate("MainWindow", "Manual edition", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditManual.setToolTip(QtGui.QApplication.translate("MainWindow", "Manually edit fibres position", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditManual.setStatusTip(QtGui.QApplication.translate("MainWindow", "Manually edit fibres position", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh.setToolTip(QtGui.QApplication.translate("MainWindow", "Refresh view", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh.setStatusTip(QtGui.QApplication.translate("MainWindow", "Refresh view", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveSimscreen.setText(QtGui.QApplication.translate("MainWindow", "Save (SIMSCREEN)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveSimscreen.setToolTip(QtGui.QApplication.translate("MainWindow", "Saves current microstructure in Simscreen format", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveSimscreen.setStatusTip(QtGui.QApplication.translate("MainWindow", "Click to save in Simscreen format", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveSimscreen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenSimscreen.setText(QtGui.QApplication.translate("MainWindow", "Open (SIMSCREEN)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenSimscreen.setToolTip(QtGui.QApplication.translate("MainWindow", "Opens microstructure in Simscreen format", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenSimscreen.setStatusTip(QtGui.QApplication.translate("MainWindow", "Click to open Simscreen format", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenSimscreen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNNA.setText(QtGui.QApplication.translate("MainWindow", "NNA", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDiameters.setText(QtGui.QApplication.translate("MainWindow", "Diameters", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRDF.setText(QtGui.QApplication.translate("MainWindow", "G function (RDF)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLocal_volume_fraction.setText(QtGui.QApplication.translate("MainWindow", "Local volume fraction", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
